config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    path: 'admin',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    },
    controllers: {
      sessions: 'admin/sessions',
      passwords: 'admin/passwords'
    },
    skip: [:registration]

  devise_for :customers,
    path: 'customer',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    },
    controllers: {
      sessions: 'customers/sessions',
      passwords: 'customers/passwords'
    },
    skip: [:registration]

  root 'properties#index'

  get '/home' => 'pages#home'

  get '/bodelningsavtal' => 'properties#new', as: :new_property

  resources :properties, except: [:new] do
    resources :property_reports, only: [:index], as: 'reports'
    get 'docx' => 'property_reports#docx', as: :reports_docx
  end

  resource :property, only: [:edit, :update, :destroy], as: :customers_property
  get '/property_report' => 'property_reports#index', as: :customers_property_report

  namespace :admin do
    root to: 'orders#index'

    resources :orders, only: [:index]
    resources :users, except: [:show]
  end

  namespace :customers, path: 'customer' do
    root to: 'properties#index'
  end
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :customer, optional: true

  def data *path
    if path.empty?
      self[:data]
    else
      self.send("data[#{ path.map(&:to_s).join('][') }]")
    end
  end

  def fetch *path, default
    self.send("data[#{ path.map(&:to_s).join('][') }]") || default
  end

  def method_missing method_sym, *opts
    method = method_sym.to_s

    if method.starts_with? 'data[' and method.ends_with? ']'
      path = method[5..-2].split ']['
      result = data.dig *path rescue nil
      return result
    end

    raise NoMethodError, "undefined method `#{method}` for #{self.class.name}"
  end

  def sorted property_type
    return {} if data(property_type).blank?

    data(property_type)
      .inject({}) do |result, (type, properties)|
        properties.each do |id, property|
          result[id] = property
          result[id]['type'] = type
        end
        result
      end
      .sort_by { |k, v| k }
      .to_h
  end

  def sorted_assets; sorted :assets end
  def sorted_debts;  sorted :debts  end

  def property_compensation
    data['compensation']['decide']
  end

  def compensation_amount
    data['payment']['how_much'].to_i
  end

  def compensation_reciever
    data['payment']['to_whom'].to_sym
  end

  def compensation_giver
    compensation_reciever == :husband ? :wife : :husband
  end

  def compensate_by_law?
    true if property_compensation == 'false'
  end

  def compensation_due_date
    data['payment_details']['date']
  end

  def compensation_clearing
    data.dig('payment_details', 'field_1')
  end

  def compensation_account
    data.dig('payment_details', 'field_2')
  end

  def compensation_bank_name
    data.dig('payment_details', 'field_3')
  end

  def compensation_details_filled?
    !compensation_clearing.blank? &&
    !compensation_account.blank?  &&
    !compensation_bank_name.blank?
  end

  def interest_before?
    data['interest']['before_payment'] == 'true'
  end

  def interest_after?
    data['interest']['after_payment'] == 'true'
  end

  def interest_rate_before
    data['interest']['before_payment_rate']
  end

  def interest_rate_after
    data['interest']['after_payment_rate']
  end

  def witness_to_sign?
    witness_to_sign = data['witnesses']['to_sign']
    true if witness_to_sign == 'true'
  end

  def validated? # remove if moving away from heroku
    validated
  end

  def full_name_for(member)
    "#{data[member.to_s]['firstname']} #{data[member.to_s]['lastname']}"
  end
end

app/controllers/customers/properties_controller.rb
class Customers::PropertiesController < Customers::MainController
  def index
    @properties = Property
      .where(customer: current_customer)
      .order(created_at: :desc)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  include PropertyParamsCleanup

  before_action :set_property, only: [:edit, :update, :destroy]
  before_action :property_params_cleanup, only: [:update]

  def index
    @properties = Property.all.order(created_at: :desc)
  end

  def new
    @property = Property.create customer: current_customer
    redirect_to edit_property_path @property
  end

  def edit
    render :form
  end

  def update
    @property.update_attributes property_params
    if request.xhr?
      render plain: 'ok'
    else
      redirect_to after_form_path, flash: { notice: 'Form was saved successfully' }
    end
  end

  def destroy
    @property.destroy
    redirect_to after_form_path
  end

    private

      def set_property
        @property =
          if params[:id].present?
            Property.find params[:id]
          elsif customer_signed_in?
            current_customer.properties.first
          end
      end

      def create_customer
        @customer = Customer.create customer_params
        sign_in @customer, scope: :customer
      end

      def set_customer
        params[:property][:customer_id] = current_customer.id
      end

      def after_form_path
        if customer_signed_in?
          customers_root_path
        else
          properties_path
        end
      end

      def property_params
        params
          .require(:property)
          .permit!
      end

      def customer_params
        params
          .require(:customer)
          .permit([:email, :password])
      end
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def property_panel type, opts = {}, &block
    """
    <div class='panel panel-bordered #{opts.dig :panel, :class}'>
      <div class='panel-heading #{opts.dig :heading, :class}'>
        <div class='h3 panel-title'>
          #{ I18n.t "property.#{type}.header" }
        </div>
      </div>
      <div class='panel-body #{opts.dig :body, :class}'>
        #{ capture &block }
      </div>
    </div>
    """.html_safe
  end

  def property_member_years
    ( (Date.today.year - 100)..(Date.today.year - 12) )
      .map { |year| [year, year] }
  end

  def property_member_months
    I18n.t('date.month_names', locale: :sv)
      .compact
      .each_with_index
      .map { |month, index| ["#{month} (#{index + 1})", index + 1] }
  end

  def property_member_days
    ( 1..31 )
      .map { |day| [day, day] }
  end

  def property_number_of_copies
    recommended = 4
    ( 2..10 )
      .map { |n|
        if n == recommended
        then ["#{n} (#{t 'property.copies.copies_recommended'})", n]
        else [n, n]
        end
      }
  end

  def prop_type_match type, tab
    type.to_s == tab.to_s
  end

  def hidden_unless data_value
    'display: none;' unless data_value == 'true'
  end

  def hidden_unless_in data_value, true_options
    'display: none;' unless true_options.include? data_value
  end

  def asset_partial id = nil, type = ''
    render partial: "properties/form/assets_and_debts/asset",
      locals: {
        id: id || Time.now.to_i.to_s,
        type: type
      }
  end

  def debt_partial id = nil, type = ''
    render partial: "properties/form/assets_and_debts/debt",
      locals: {
        id: id || Time.now.to_i.to_s,
        type: type
      }
  end

  def faq_section key
    render partial: 'properties/faq',
      locals: {
        faq: key
      }
  end
end

app/views/properties/_faq.html.slim
- body = t "#{faq}"

.faq
  .btn.btn-link.px-0 = t "property.faq.label"

  .faq-body style='display: none;'
    - body.each do |key, text|
      - if key.to_s.starts_with? 'q'
        .faq-question.h4 = text.html_safe
      - else
        .faq-answer = text.html_safe

app/views/properties/_form.html.slim
.fieldset-group [
  data-hide-progress='true'
]
  fieldset [
    data-group='instructions'
    data-next-btn-label=t('property.submit.start_now')
    data-prev-btn-hide='true'
  ]
    .row
      .col
        == render 'properties/form/instructions'

  fieldset [
    data-group='warning'
    data-next-btn-label=t('property.submit.continue')
    data-prev-btn-hide='true'
  ]
    .row
      .col
        == render 'properties/form/warning'

.fieldset-group [
  data-title=t('property.groups.general')
  data-icon=image_path('customers/group1.svg')
]
  fieldset [
    data-title=t('property.subgroups.members')
    data-group='members'
  ]
    .row
      .col
        == render 'properties/form/members'

  fieldset [
    data-title=t('property.subgroups.copies')
    data-group='copies'
  ]
    .row
      .col
        == render 'properties/form/copies'

  fieldset [
    data-title=t('property.subgroups.witnesses')
    data-group='witnesses'
  ]
    .row
      .col
        == render 'properties/form/witnesses'

  fieldset [
    data-title=t('property.subgroups.court')
    data-group='court'
  ]
    .row
      .col
        == render 'properties/form/court'

.fieldset-group [
  data-title=t('property.groups.assets')
  data-icon=image_path('customers/group2.svg')
]
  fieldset [
    data-title=t('property.subgroups.any_assets')
    data-group='any_assets'
  ]
    .row
      .col
        == render 'properties/form/any_assets'

  fieldset [
    data-title=t('property.subgroups.assets')
    data-skip=( @property.data(:assets_debts, :any_assets) != 'true' ).to_s
    data-group='assets'
  ]
    .row
      .col
        == render 'properties/form/assets'

.fieldset-group [
  data-title=t('property.groups.debts')
  data-icon=image_path('customers/group3.svg')
]
  fieldset [
    data-title=t('property.subgroups.any_debts')
    data-group='any_debts'
  ]
    .row
      .col
        == render 'properties/form/any_debts'

  fieldset [
    data-title=t('property.subgroups.debts')
    data-skip=( @property.data(:assets_debts, :any_debts) != 'true' ).to_s
    data-group='debts'
  ]
    .row
      .col
        == render 'properties/form/debts'

.fieldset-group [
  data-title=t('property.groups.compensation')
  data-icon=image_path('customers/group4.svg')
]
  fieldset [
    data-title=t('property.compensation.header')
    data-group='compensation'
  ]
    .row
      .col
        == render 'properties/form/compensation'

    .row.if-compensation style="#{ hidden_unless @property.data(:compensation, :decide) }"
      .col
        == render 'properties/form/payment'

    .row.if-compensation-details style="#{ hidden_unless_in @property.data(:compensation, :decide), ['true', 'false'] }"
      .col
        == render 'properties/form/payment_details'

    .row.if-compensation-details style="#{ hidden_unless_in @property.data(:compensation, :decide), ['true', 'false'] }"
      .col
        == render 'properties/form/interest'

.fieldset-group [
  data-title=t('property.groups.other')
  data-icon=image_path('customers/group5.svg')
]
  fieldset [
    data-group='other'
    data-next-btn-label=t('property.submit.save_and_create')
  ]
    .row
      .col
        == render 'properties/form/other'

= hidden_field_tag 'property[data[form][last_fieldset]]', @property.data(:form, :last_fieldset) || 0
= hidden_field_tag :submit_type, 'hard'


.form-actions.d-none
  button.form-prev.btn.btn-default.ml-20.mb-10
    = t 'property.submit.previous'

  button.form-next.btn.btn-success.ml-20.mb-10 data-default-label=t('property.submit.save_and_continue')
    = t 'property.submit.save_and_continue'

  - if @property.validated?
    button.form-save.btn.btn-success.ml-20.mb-10
      = t 'property.submit.save_and_quit'

app/views/properties/_signup.html.slim
= property_panel 'signup' do
  .row
    .col-md
      .form-group
        label = t('property.signup.email')
        = email_field_tag 'customer[email]', nil,
          class: 'form-control',
          data: { \
            parsley_required: true,
            parsley_validate_if_empty: true,
            parsley_error_message: t('property.error.required') }

    .col-md
      .form-group
        label = t('property.signup.password')
        = password_field_tag 'customer[password]', nil,
          class: 'form-control',
          autocomplete: 'new-password',
          data: { \
            parsley_required: true,
            parsley_validate_if_empty: true,
            parsley_error_message: t('property.error.required') }

app/views/properties/edit.html.slim
.container
  .property-form
    == form_for @property, method: :patch do |f|

      - @f = f

      == render "form"

app/views/properties/form.html.slim
.container
  .text-center.mt-50.mb-4
    = image_tag 'customers/logo.svg'

  .property-form
    .form-progress
      .h3 = t('property.progress.header')
      .steps

    == form_for @property, remote: true, authenticity_token: true do |f|
      - @f = f
      == render "form"

app/views/properties/index.html.slim
.container
  .property-listing.mt-50
    .panel.panel-bordered
      .panel-heading
        h3.panel-title
          | Division of property forms
          .float-right.mt--8
            = link_to new_property_path, class: 'btn btn-primary'
              | Create new bodelningsavtal
      .panel-body
        - if @properties.blank?
          .h5.text-center.my-10
            | No forms here yet
        - else
          table.table
            - @properties.each do |property|
              tr
                td.main
                  - if property.validated?
                    i.fa.fa-check.fa-fw.text-success
                  - else
                    i.fa.fa-fw.text-success
                  | Bodelningsavtal ##{property.id}

                td
                  = link_to edit_property_path(property), class: 'btn btn-primary btn-sm'
                    i.fa.fa-pencil
                td
                  = link_to property_path(property), method: :delete, class: 'btn btn-danger btn-sm', 'data-confirm' => 'Are you sure?'
                    i.fa.fa-trash
                - if property.validated?
                  td
                    = link_to 'Download PDF', property_reports_path(property), class: 'btn btn-success ml-10', target: '_blank'
                  td
                    = link_to 'Download DOCX', property_reports_docx_path(property), class: 'btn btn-success ml-10', download: "property_#{property.id}.docx"
                - else
                  td
                    = link_to 'Download PDF', '#', class: 'btn btn-success disabled ml-10 tool-tip', data: {:"original-title" => "Please complete the form to generate the files", :toggle => "tooltip", :placement => 'bottom'}
                  td
                    = link_to 'Download DOCX', '#', class: 'btn btn-success disabled ml-10 tool-tip', data: {:"original-title" => "Please complete the form to generate the files", :toggle => "tooltip", :placement => 'bottom'}


css:
  .btn {
    pointer-events: all !important;
  }

javascript:
  $(document).ready(function() {
    $('[data-toggle="tooltip"]').tooltip();
  });